modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="dtphc2"
version="${file.jarVersion}"
displayName="Dynamic Trees for PHC2"
#updateJSONURL="https://github.com/supermassimo/DynamicTrees-ExC/blob/1.12.2/.DONE/DynamicTrees-BYG/version_info.json?raw=true" #optional
#displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-byg" #optional
logoFile="logo.png"
credits="Max Hyper and ChefExperte"
authors="Max Hyper"
description='''
Compatibility Mod between Dynamic Trees and Pam's HarvestCraft 2: Trees
'''

[[dependencies.dtphc2]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtphc2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtphc2]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.11.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtphc2]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtphc2]]
    modId="pamhc2trees"
    mandatory=true
    versionRange="[1.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtphc2]]
    modId="dtbyg"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dtbop"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dtbop"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dttraverse"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dtterraforged"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dtautumnity"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dtmysticalbiomes"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
[[dependencies.dtphc2]]
    modId="dtvoyage"
    mandatory=false
    versionRange="(0.0,)"
    ordering="AFTER"
